### ISSUE TITLE
Unable to Progress ahead due to unable to signin 

### ISSUE THREAD

**Issue by Takeru9016** [joschan21/digitalhippo#13]
Video timestamp: 05:10:00

I cant progress ahead deu to when I sign in , It work as I get that toast notification of successful sign and I also get the cookies(jwt token).

But when It takes me to homepage and it doesn't remove the sign in & create account button.

Here is current Navbar.tsx - 
![Navbar](https://github.com/joschan21/digitalhippo/assets/71886594/f3226645-3864-4744-997f-cfbef35380ba)
Here is current payload-util.ts - 
![payload-util](https://github.com/joschan21/digitalhippo/assets/71886594/b0ea2410-6094-4ecd-ab74-5900562365e5)

**Comment by ghost** [comment]
i have the same problem. i cant find the solution

**Comment by ghost** [comment]
Go to the Sign In page.  Once there, go ahead and change the position of the router.refresh( ) and put it under the router.push. After login, it will push you to the home page and then reload the page so the buttons will be hidden after it.
`router.push('/')`
`router.refresh()
            }, `

**Comment by Takeru9016** [comment]
> Go to the Sign In page. Once there, go ahead and change the position of the router.refresh( ) and put it under the router.push. After login, it will push you to the home page and then reload the page so the buttons will be hidden after it. `router.push('/')` `router.refresh() }, `

It worked. Thank You but when I check it on my chrome it doesn't display the UserAccountNav.tsx page but when checked on Firefox it works. So is it browser issue here ?

**Comment by ghost** [comment]
> > Go to the Sign In page. Once there, go ahead and change the position of the router.refresh( ) and put it under the router.push. After login, it will push you to the home page and then reload the page so the buttons will be hidden after it. `router.push('/')` `router.refresh() }, `
> 
> It worked. Thank You but when I check it on my chrome it doesn't display the UserAccountNav.tsx page but when checked on Firefox it works. So is it browser issue here ?

Don’t think so. Just double check ur code. It must work in all the browsers because it’s not something related to it.

**Comment by itzTedx** [comment]
> Go to the Sign In page. Once there, go ahead and change the position of the router.refresh( ) and put it under the router.push. After login, it will push you to the home page and then reload the page so the buttons will be hidden after it. `router.push('/')` `router.refresh() }, `

Yes. This solution worked

**Comment by ghost** [comment]
> Go to the Sign In page. Once there, go ahead and change the position of the router.refresh( ) and put it under the router.push. After login, it will push you to the home page and then reload the page so the buttons will be hidden after it. `router.push('/')` `router.refresh() }, `

thanks for helping !
