### ISSUE TITLE
How to get free domain for test  while making auth verification in resend ?

### ISSUE THREAD

**Issue by adarshchhetri9** [joschan21/digitalhippo#29]
I have been stuck in the project because i can't complete the auth verification since i don't have custom domain and after the hours and days of making on this project . So do anyone know how to do auth verification and token process if i don't have domain to use in resend.

**Comment by BenDaver** [comment]
you could set the 
_verified: true in the db.

this will make the user verified without using the email veification

**Comment by adarshchhetri9** [comment]
@BenDaver Ohhh ok. Thanks man!
