### ISSUE TITLE
PrimaryActionEmail Image not provided

### ISSUE THREAD

**Issue by kaleembhattiworks** [joschan21/digitalhippo#30]
Inside the `PrimaryActionEmail` component there is an image being loaded with the path `{${process.env.NEXT_PUBLIC_SERVER_URL}/hippo-newsletter-sign-up.png}`, 
however
there is no such image provided inside the public folder.

**Comment by suryansh098** [comment]
![hippo-newsletter-sign-up](https://github.com/joschan21/digitalhippo/assets/55638070/ffe29e4d-8891-4fbd-999e-ab9c7ea868f2)
