### ISSUE TITLE
"My Account" drop-down menu not showing after Sign-In

### ISSUE THREAD

**Issue by mvdgn** [joschan21/digitalhippo#5]
I have to manually refresh the page after sign-in to see the "My Account" drop-down menu in the navigation bar even if I am redirected to the homepage.
In the video, after sign-in, the “My account” drop-down menu appears immediately when redirected to the homepage.

Can you tell me what could be causing this problem? I have tried everything. This is certainly a small detail.

THANKS.

**Comment by JackDuckar** [comment]
Got the same issue. I made some replacement in (auth)/sign-in/page.tsx (so you refresh router after redirecting on '/')
Remove router.refresh() after toast.succes(....) and put it after router.push('/') in the end of onSucess function

**Comment by mvdgn** [comment]
Awesome ! Thank you very much Jack. I appreciate your help.
Cheers
