### ISSUE TITLE
dev script doesn't compile tailwind

### ISSUE THREAD

**Issue by volfadar** [joschan21/digitalhippo#6]
hello everyone!

i might be wrong or miss something, but the "npm run dev" script that executes "cross-env PAYLOAD_CONFIG_PATH=src/payload.config.ts nodemon" only compile the ts file, there's no tailwind hot reload compiler command that needs to be executed. how to improve this script to make it also run a tailwind CSS compiler. or if it needs to be split, then how to do it?

thankss

**Comment by devlopersabbir** [comment]
@volfadar have you done your `nodemon.json` file??

I just changed the folder and file structure slightly but you can follow Josh way.
Here is my `nodemon.json` file code.
```json
{
  "watch": ["server.ts", "src/collections/**/*.ts", "src/tRPC/appRouter.ts"],
  "exec": "ts-node --project tsconfig.server.json src/servers/server.ts -- -I",
  "ext": "js ts",
  "stdin": false
}
```
**TODO**
- **watch** set your watch file based on your file structure
- **exec** also your execution location

**Comment by volfadar** [comment]
Ah, very well, thanks, bro! I customized the structure a bit, but I forgot to include that file in the watch parameters. 🤦‍♂️
